<a href="https://colab.research.google.com/github/ReImage-CollegeProject/Learn_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/



Discussion: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
print("hello world pytorch")

hello world pytorch


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.1.0+cu118


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensor

### creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar

scalar  = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim       # scalar has 0 dimension so

0

In [ ]:
# Get tensor back as Python int

scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

# Tensor

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
SOME_TENSOR = torch.tensor([[[[[[1,2,3],
                                [3,4,5],
                                [6,9,4]]]]]])

In [ ]:
SOME_TENSOR.ndim

6

In [ ]:
SOME_TENSOR.shape

torch.Size([1, 1, 1, 1, 3, 3])

In [ ]:
AN_TENSOR = torch.tensor([[12,33,4],[2,3,4]])

In [ ]:
AN_TENSOR.ndim

2

### Random Tensors

Why random tensors?

Random tensors are important beacause the way many neural network learn is what they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

### creating random tensor using PyTorch

Link: https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3522, 0.1368, 0.2817, 0.1211],
        [0.5047, 0.4181, 0.8368, 0.2210],
        [0.4576, 0.7385, 0.6454, 0.4345]])

In [ ]:
random_tensor.ndim

2

In [ ]:

random_tensor.shape

torch.Size([3, 4])

In [ ]:

# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 4)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 4]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.5207, 0.2782, 0.0717, 0.9958],
         [0.1702, 0.7562, 0.1956, 0.9814],
         [0.0497, 0.5231, 0.7219, 0.9257],
         ...,
         [0.1518, 0.2648, 0.8569, 0.7331],
         [0.7081, 0.4363, 0.9602, 0.6237],
         [0.8607, 0.8414, 0.2684, 0.0145]],

        [[0.5329, 0.5919, 0.0253, 0.1929],
         [0.5687, 0.6670, 0.6746, 0.0015],
         [0.9635, 0.9824, 0.6444, 0.7430],
         ...,
         [0.3013, 0.9295, 0.4465, 0.4685],
         [0.2973, 0.2193, 0.5570, 0.3410],
         [0.1948, 0.7499, 0.2223, 0.3352]],

        [[0.4279, 0.9275, 0.3805, 0.6040],
         [0.9452, 0.2033, 0.7614, 0.1975],
         [0.0996, 0.5202, 0.3382, 0.7749],
         ...,
         [0.4441, 0.8075, 0.2952, 0.5517],
         [0.2404, 0.1313, 0.5755, 0.7578],
         [0.3470, 0.8664, 0.1817, 0.4555]],

        ...,

        [[0.3488, 0.5726, 0.9622, 0.5057],
         [0.5672, 0.3797, 0.7336, 0.5629],
         [0.7000, 0.1754, 0.3396, 0.8293],
         ...,
         [0.9205, 0.5

# Exercise
Creating tensor of any size for experimentation

In [ ]:
myTensor = torch.rand(4,2)
myTensor, myTensor,

(tensor([[0.5457, 0.8836],
         [0.0387, 0.5717],
         [0.8454, 0.0389],
         [0.2371, 0.0532]]),
 tensor([[0.5457, 0.8836],
         [0.0387, 0.5717],
         [0.8454, 0.0389],
         [0.2371, 0.0532]]))

In [ ]:
torch.rand(size=(3,4))

tensor([[0.0157, 0.4723, 0.9697, 0.6380],
        [0.6020, 0.5936, 0.3727, 0.1970],
        [0.5579, 0.9040, 0.0241, 0.8613]])

## Zeros and Ones

In [ ]:
# create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors-like

In [ ]:
# use torch.range() and get deprecated message so use torch.arange()
torch.range(0,10)

<ipython-input-202-422f24684e88>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.6, 4.2, 6.9, 9.6],
                               dtype=None,      # what datatype is tensor (e.g. float32, float 16)
                               device=None,     # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations


In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.5996, 4.1992, 6.8984, 9.6016], dtype=torch.float16)

In [ ]:
some_tensor = float_16_tensor * float_32_tensor
some_tensor

tensor([12.9586, 17.6367, 47.5992, 92.1750])

In [ ]:
some_tensor.dtype, some_tensor.device, some_tensor.shape

(torch.float32, device(type='cpu'), torch.Size([4]))

In [ ]:
int_32_tensor = torch.tensor([6,9,4,2], dtype=torch.int32)
int_32_tensor

tensor([6, 9, 4, 2], dtype=torch.int32)

In [ ]:
res_tensor = float_32_tensor * int_32_tensor
print(res_tensor)
res_tensor.dtype,  res_tensor.shape

tensor([21.6000, 37.8000, 27.6000, 19.2000])


(torch.float32, torch.Size([4]))

### Getting information from Tensor (tensor attributes)

1. Tensors not right datatype - to get data type from a tensor, we can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, we can use `tensor.shape`

3. Tensor not on the right device - to get device from a tensor, we can use `tensor.device`


In [ ]:
# create a tensor
some_tensor  = torch.rand(3,4, device="cpu", dtype=torch.float32)

In [ ]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# find out some details about the tensor
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6567, 0.1795, 0.2272, 0.0956],
        [0.1640, 0.1165, 0.6777, 0.2917],
        [0.2856, 0.5917, 0.7249, 0.4167]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (**tensor operations**):

Tensor operations includde:
* Addition
* Subtraction
* Multiplication( element-wise)
* Division
* Matrix Multiplication

In [ ]:
## create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
## multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
## subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
## try out PyTorch in-build functions
torch.mul(tensor,10) # multiply by 10

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,2) # add 2 to tensor

tensor([3, 4, 5])

In [ ]:
torch.sub(tensor, 10) # subtract tensor from 10

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication / dot product (most common multiplication)



There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (2,3)` won't work


2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.5551, 0.6657, 0.7378],
        [0.9731, 0.5904, 0.9967],
        [1.0535, 0.7370, 1.1294]])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 1.71 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 183 µs, sys: 0 ns, total: 183 µs
Wall time: 191 µs


tensor(14)

### One of the most common error in deep learning ar

https://matrixmultiplication.xyz

In [ ]:
#  Shpes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B)     # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# to fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
## The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shape : tensor_A = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

print(f"\nOutput shape: {output.shape}\n")


torch.mm(tensor_A, tensor_B.T)

Original shape : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shape : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])



tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor aggregation
### finding the min, max, mean, sum, etc.

In [ ]:
# create a tensor
x = torch.arange(0,100,10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0.), tensor(0.))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(90.), tensor(90.))

In [ ]:
# find the mean : NOTE: the `torch.mean()` function requires a tensor of float32 data type to work
torch.mean(x), x.mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the mean