<a href="https://colab.research.google.com/github/ReImage-CollegeProject/Learn_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pytorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/



Discussion: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
print("hello world pytorch")

hello world pytorch


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.1.0+cu118


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensor

### creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar

scalar  = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim       # scalar has 0 dimension so

0

In [ ]:
# Get tensor back as Python int

scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

# Tensor

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
SOME_TENSOR = torch.tensor([[[[[[1,2,3],
                                [3,4,5],
                                [6,9,4]]]]]])

In [ ]:
SOME_TENSOR.ndim

6

In [ ]:
SOME_TENSOR.shape

torch.Size([1, 1, 1, 1, 3, 3])

In [ ]:
AN_TENSOR = torch.tensor([[12,33,4],[2,3,4]])

In [ ]:
AN_TENSOR.ndim

2

### Random Tensors

Why random tensors?

Random tensors are important beacause the way many neural network learn is what they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

### creating random tensor using PyTorch

Link: https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2052, 0.3981, 0.0160, 0.2731],
        [0.9250, 0.0606, 0.9168, 0.2466],
        [0.7639, 0.6137, 0.6267, 0.5795]])

In [ ]:
random_tensor.ndim

2

In [ ]:

random_tensor.shape

torch.Size([3, 4])

In [ ]:

# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 4)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 4]), 3)

In [ ]:
random_image_size_tensor

tensor([[[5.2445e-02, 5.8635e-01, 3.8473e-01, 5.0250e-02],
         [7.7300e-01, 9.8747e-01, 3.4640e-01, 2.9744e-01],
         [1.9762e-02, 6.0307e-01, 6.0053e-01, 9.8027e-01],
         ...,
         [8.7832e-01, 3.1772e-01, 4.1542e-01, 5.4752e-02],
         [1.9661e-01, 9.8406e-01, 6.3758e-01, 6.4827e-01],
         [9.2873e-01, 9.7439e-01, 1.9271e-01, 9.5985e-01]],

        [[8.4687e-01, 4.8546e-01, 8.7452e-01, 3.6045e-01],
         [7.4077e-02, 1.6478e-01, 6.3043e-01, 7.2933e-01],
         [7.2619e-01, 1.6769e-01, 5.4128e-01, 9.5612e-01],
         ...,
         [7.8419e-01, 8.8248e-02, 3.9485e-01, 8.7470e-01],
         [6.8498e-04, 5.1420e-01, 3.0424e-01, 6.4107e-01],
         [4.3747e-01, 7.3705e-01, 1.5898e-01, 9.4686e-01]],

        [[9.9075e-01, 6.8644e-01, 5.9591e-01, 9.8516e-01],
         [7.1053e-01, 2.4054e-01, 7.6130e-01, 9.8798e-01],
         [3.3123e-02, 7.3869e-01, 6.5577e-01, 2.6603e-01],
         ...,
         [1.0206e-01, 6.0299e-01, 6.0617e-01, 4.4373e-01],
         [

# Exercise
Creating tensor of any size for experimentation

In [ ]:
myTensor = torch.rand(4,2)
myTensor, myTensor,

(tensor([[0.9381, 0.3232],
         [0.4607, 0.4363],
         [0.7024, 0.9812],
         [0.0574, 0.1926]]),
 tensor([[0.9381, 0.3232],
         [0.4607, 0.4363],
         [0.7024, 0.9812],
         [0.0574, 0.1926]]))

In [ ]:
torch.rand(size=(3,4))

tensor([[0.9161, 0.6788, 0.6707, 0.0659],
        [0.0045, 0.3775, 0.8660, 0.6580],
        [0.3612, 0.9770, 0.2196, 0.8992]])

## Zeros and Ones

In [ ]:
# create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors-like

In [ ]:
# use torch.range() and get deprecated message so use torch.arange()
torch.range(0,10)

<ipython-input-101-422f24684e88>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.6, 4.2, 6.9, 9.6],
                               dtype=None,      # what datatype is tensor (e.g. float32, float 16)
                               device=None,     # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations


In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.5996, 4.1992, 6.8984, 9.6016], dtype=torch.float16)

In [ ]:
some_tensor = float_16_tensor * float_32_tensor
some_tensor

tensor([12.9586, 17.6367, 47.5992, 92.1750])

In [ ]:
some_tensor.dtype, some_tensor.device, some_tensor.shape

(torch.float32, device(type='cpu'), torch.Size([4]))

In [ ]:
int_32_tensor = torch.tensor([6,9,4,2], dtype=torch.int32)
int_32_tensor

tensor([6, 9, 4, 2], dtype=torch.int32)

In [ ]:
res_tensor = float_32_tensor * int_32_tensor
print(res_tensor)
res_tensor.dtype,  res_tensor.shape

tensor([21.6000, 37.8000, 27.6000, 19.2000])


(torch.float32, torch.Size([4]))

### Getting information from Tensor (tensor attributes)

1. Tensors not right datatype - to get data type from a tensor, we can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, we can use `tensor.shape`

3. Tensor not on the right device - to get device from a tensor, we can use `tensor.device`


In [ ]:
# create a tensor
some_tensor  = torch.rand(3,4, device="cpu", dtype=torch.float32)

In [ ]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
# find out some details about the tensor
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4330, 0.0421, 0.8349, 0.5157],
        [0.7433, 0.9813, 0.7194, 0.8682],
        [0.0212, 0.9260, 0.1632, 0.5780]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (**tensor operations**):

Tensor operations includde:
* Addition
* Subtraction
* Multiplication( element-wise)
* Division
* Matrix Multiplication

In [ ]:
## create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
## multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
## subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
## try out PyTorch in-build functions
torch.mul(tensor,10) # multiply by 10

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,2) # add 2 to tensor

tensor([3, 4, 5])

In [ ]:
torch.sub(tensor, 10) # subtract tensor from 10

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication / dot product (most common multiplication)



There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (2,3)` won't work


2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.2844, 0.2384, 0.2437],
        [0.2813, 0.3066, 0.3380],
        [0.8617, 0.7240, 0.7405]])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.87 ms, sys: 0 ns, total: 1.87 ms
Wall time: 3.19 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 101 µs, sys: 0 ns, total: 101 µs
Wall time: 107 µs


tensor(14)

### One of the most common error in deep learning ar

https://matrixmultiplication.xyz

In [ ]:
#  Shpes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B)     # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# to fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
## The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shape : tensor_A = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

print(f"\nOutput shape: {output.shape}\n")


torch.mm(tensor_A, tensor_B.T)

Original shape : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shape : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])



tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor aggregation
### finding the min, max, mean, sum, etc.

In [ ]:
import torch

In [ ]:
# create a tensor
x = torch.arange(0,100,10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0.), tensor(0.))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(90.), tensor(90.))

In [ ]:
# find the mean : NOTE: the `torch.mean()` function requires a tensor of float32 data type to work
torch.mean(x), x.mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

## finding the positional min and max

In [ ]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
## find the postion in tensor that has the minimum value with argmin() -> returns the index position of target tensor where the minimu value occures
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0.)

In [ ]:
## find the position in tensor that has maximu  value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90.)

In [ ]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapeds an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but keep tha same memory as the original tensor
* Stacking - combine the multple  tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - returns a view of the input with dimension permuted(swapped) in a certain way



In [ ]:
## creating a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape,

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape((1,9))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the orignal input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x.ndim

1

In [ ]:

# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# Stack tensor on top of each other
# x_stacked = torch.stack([x, x, x, x], dim=)   # this produces error `IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)`
# x_stacked

In [ ]:
# torch.squeeze() - removes all the single dimensions from a target *tensor*
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")



Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to target tensor at a specific dimension
print(f"Previous targed: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Squeezed Tensor : {x_unsqueezed}")
print(f"New Squeezed shape: {x_unsqueezed.shape}")

Previous targed: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Squeezed Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Squeezed shape: torch.Size([1, 9])


In [ ]:
# torch.permute() -- rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the orignal tensor to rearrage the axis (or dim) or order
x_permuted = torch.permute(x_original,[2, 0, 1])   # shifts the axis 0->1, 1->2 and 2->0
# x_permuted = x_original.permute(2, 0, 1)   # shifts the axis 0->1, 1->2 and 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_new = x_original.permute([2,0,1])
print(f"x_original shape : {x_original.shape}")
print(f"x_new shape : {x_new.shape}")

x_original shape : torch.Size([224, 224, 3])
x_new shape : torch.Size([3, 224, 224])


In [ ]:
x_original[:, :, :]

tensor([[[0.2920, 0.7048, 0.4679],
         [0.5033, 0.1183, 0.0698],
         [0.0158, 0.0870, 0.0370],
         ...,
         [0.3089, 0.2342, 0.3398],
         [0.9800, 0.1234, 0.8071],
         [0.1167, 0.7539, 0.2283]],

        [[0.2743, 0.4649, 0.3584],
         [0.9758, 0.0145, 0.8955],
         [0.1447, 0.9751, 0.2876],
         ...,
         [0.2076, 0.5101, 0.6858],
         [0.3535, 0.8822, 0.5391],
         [0.5830, 0.1542, 0.0750]],

        [[0.0741, 0.7101, 0.5454],
         [0.3470, 0.4038, 0.6601],
         [0.4927, 0.2346, 0.6352],
         ...,
         [0.9848, 0.3812, 0.4026],
         [0.7813, 0.6542, 0.8385],
         [0.0880, 0.6406, 0.8749]],

        ...,

        [[0.9886, 0.9110, 0.4350],
         [0.3460, 0.9001, 0.4590],
         [0.6042, 0.1292, 0.2238],
         ...,
         [0.0023, 0.4511, 0.6085],
         [0.4647, 0.2605, 0.1605],
         [0.8607, 0.7394, 0.2890]],

        [[0.5085, 0.2119, 0.4589],
         [0.7806, 0.9071, 0.1030],
         [0.

In [ ]:
x_original[:,:,0]

tensor([[0.4313, 0.8700, 0.6883,  ..., 0.7593, 0.3433, 0.6542],
        [0.0771, 0.1252, 0.0567,  ..., 0.1975, 0.2904, 0.2766],
        [0.7207, 0.7048, 0.1708,  ..., 0.5379, 0.2220, 0.0263],
        ...,
        [0.8522, 0.6503, 0.2598,  ..., 0.2212, 0.6889, 0.2867],
        [0.2451, 0.2722, 0.3941,  ..., 0.7732, 0.3720, 0.1873],
        [0.6290, 0.5249, 0.8767,  ..., 0.6220, 0.5426, 0.2301]])

In [ ]:
x_original[:,:,:]

tensor([[[0.4313, 0.8400, 0.2239],
         [0.8700, 0.6104, 0.9950],
         [0.6883, 0.6537, 0.3383],
         ...,
         [0.7593, 0.5176, 0.3601],
         [0.3433, 0.9407, 0.5758],
         [0.6542, 0.6973, 0.8342]],

        [[0.0771, 0.6215, 0.3664],
         [0.1252, 0.6305, 0.4735],
         [0.0567, 0.7638, 0.5320],
         ...,
         [0.1975, 0.2701, 0.7154],
         [0.2904, 0.8196, 0.4515],
         [0.2766, 0.2389, 0.2149]],

        [[0.7207, 0.9200, 0.7860],
         [0.7048, 0.5379, 0.0433],
         [0.1708, 0.4409, 0.5095],
         ...,
         [0.5379, 0.5430, 0.2342],
         [0.2220, 0.4058, 0.3683],
         [0.0263, 0.3461, 0.9233]],

        ...,

        [[0.8522, 0.7089, 0.1462],
         [0.6503, 0.3053, 0.9227],
         [0.2598, 0.6087, 0.4292],
         ...,
         [0.2212, 0.8408, 0.8549],
         [0.6889, 0.3347, 0.3885],
         [0.2867, 0.3506, 0.0915]],

        [[0.2451, 0.1347, 0.2393],
         [0.2722, 0.7000, 0.2072],
         [0.

In [ ]:
x_permuted[0, 0, 0] = 3
x_original[0, 0, 0], x_permuted[0, 0, 0]


(tensor(3.), tensor(3.))

In [ ]:
# some = torch.randn(2,3,5)
# some.size(), some

In [ ]:
# some_permuted =torch.permute(some, (2, 0, 1))
# some_permuted.size(), some_permuted

## Indexing (selectiin data from tensors)

Indexing with PyTorch is similar to index with NumPy.

In [ ]:
# creating a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's  index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# let's index on the most inner bracket
x[0][1][1], x[0, 1, 1]

(tensor(5), tensor(5))

In [ ]:
# Challege to get number : 9
x[0][2][2], x[0, 2, 2]

(tensor(9), tensor(9))

In [ ]:
# ":" can also be used to select the target dimension
x[:, 1]

tensor([[4, 5, 6]])

In [ ]:
# get all the values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9
x[0,2,2], x


(tensor(9),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [ ]:
# index on x to return 3, 6, 9

x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

Numpy is a popular scientific Python numberical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tension -> `torch.from_numpy(ndarray)`
* PyTorch tensor to Numpy data format -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 9.0)
tensor = torch.from_numpy(array).type(torch.float32)      # by default it returns the torch datatype with `torch.float64`
              # WARNING: when converting from numpy to pytorch, pytorch reflects numpy's default of float64, unless specifies
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
## Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
# tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# change the tensor, what happes to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

in short how a neural network learns:
`start with random number -> tensor operatiosn -> update random numbers to try and make them better representation of the data -> again -> again -> again....

To reduce the randomnes in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.


In [ ]:
torch.rand(3,3)

tensor([[0.2376, 0.7872, 0.7454],
        [0.6929, 0.3211, 0.0985],
        [0.0860, 0.9241, 0.7269]])

In [ ]:
import torch

## create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4247, 0.1353, 0.2923, 0.0580],
        [0.4460, 0.5968, 0.2196, 0.2144],
        [0.6006, 0.7958, 0.5704, 0.6043]])
tensor([[0.9804, 0.2451, 0.6487, 0.6945],
        [0.0930, 0.1670, 0.1633, 0.2685],
        [0.1025, 0.8143, 0.9819, 0.7213]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
## let's make some random but reproducible tensors

import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(3,4)

print(random_tensor_E)
print(random_tensor_C == random_tensor_E)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##  Resources for Reproducibility:
https://pytorch.org/docs/stable/notes/randomness.html

## Running tensors and PyTorch objects on the GPUs (making faster computations )


GPUs = faster computation on numbers because of CUDA + NVIDIA + PyTorch working
**bold text**


### 1. *getting* the GPU

- use colab
- use your own GPU
- use cloud computing - GCP, AWS, Azure, - rent the computers on cloud and access them


In [ ]:
!nvidia-smi

Wed Dec 13 14:30:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------


### 2. Check for GPU access with PyTorch

*italicized text*

In [ ]:
# checkt for the GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code
e.g. run on GPU if available, else default to CPU

In [ ]:
## setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
## Cound the number of devices
torch.cuda.device_count()

1

3. putting tensors (and models ) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU a results in faster computations.

In [ ]:

# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

# tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# move the tensor to GPU (if available)

tensor_on_gpu  = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy

tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:

tensor_on_cpu = tensor.to('cpu')
tensor_on_cpu, tensor_on_cpu.device