<a href="https://colab.research.google.com/github/ReImage-CollegeProject/Learn_PyTorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

In [19]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor = torch.rand(3,4)
tensor, tensor.dtype, tensor.device

(tensor([[0.8655, 0.5894, 0.6564, 0.9211],
         [0.4065, 0.8307, 0.0572, 0.2359],
         [0.9890, 0.5521, 0.3723, 0.5671]]),
 torch.float32,
 device(type='cpu'))

In [20]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device, tensor_on_gpu.dtype

(tensor([[0.8655, 0.5894, 0.6564, 0.9211],
         [0.4065, 0.8307, 0.0572, 0.2359],
         [0.9890, 0.5521, 0.3723, 0.5671]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.float32)

(tensor([2., 3., 4., 5.], device='cuda:0'),
 device(type='cuda', index=0),
 torch.float32)

(tensor([3, 4, 5, 5]), torch.int64, device(type='cpu'))

### 2. Create a random tensor with shape `(7, 7)`.


In [15]:
# Import torch

import torch

# Create random tensor
random_tensor_A = torch.rand(7,7)
random_tensor_A, random_tensor_A.ndim, random_tensor_A.size(), random_tensor_A.dtype, random_tensor_A.device

(tensor([[0.4478, 0.3479, 0.5835, 0.1932, 0.1635, 0.2397, 0.3381],
         [0.2306, 0.7390, 0.6256, 0.2438, 0.7198, 0.9323, 0.1181],
         [0.4820, 0.1010, 0.5228, 0.4566, 0.1312, 0.4200, 0.5537],
         [0.5619, 0.2351, 0.2003, 0.9458, 0.7950, 0.7336, 0.2686],
         [0.3304, 0.7321, 0.3331, 0.6881, 0.0597, 0.2772, 0.5933],
         [0.6900, 0.7859, 0.4775, 0.0871, 0.3373, 0.9501, 0.5092],
         [0.1259, 0.4754, 0.0827, 0.2503, 0.0850, 0.7520, 0.7514]]),
 2,
 torch.Size([7, 7]),
 torch.float32,
 device(type='cpu'))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [29]:
# Create another random tensor

random_tensor_B = torch.rand(1,7)

# Perform matrix multiplication
mul_res = torch.matmul(random_tensor_A, random_tensor_B.T)
mul_res, mul_res.ndim, mul_res.size(), mul_res.dtype, mul_res.device

(tensor([[1.1981],
         [1.5420],
         [1.4412],
         [1.7016],
         [1.7518],
         [1.6827],
         [1.2795]]),
 2,
 torch.Size([7, 1]),
 torch.float32,
 device(type='cpu'))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [48]:
import torch

# Set manual seed
RANDOM_SEED=0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
rand_tensor_A = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
rand_tensor_B = torch.rand(1,7)

# Matrix multiply tensors
mat_mul_res = rand_tensor_A.matmul(rand_tensor_B.T)
mat_mul_res, mat_mul_res.size(), mat_mul_res.device

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]),
 device(type='cpu'))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [51]:
# Set random seed on the GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'


CUDA_RANDOM_SEED = 42
torch.cuda.manual_seed(CUDA_RANDOM_SEED)
gpu_tensor = torch.rand(4,2, device=device)
gpu_tensor, gpu_tensor.device, gpu_tensor.dtype

(tensor([[0.6130, 0.0101],
         [0.3984, 0.0403],
         [0.1563, 0.4825],
         [0.7362, 0.4060]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.float32)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [75]:
import torch

# Set random seed
RANDOM_SEED=1234

torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2,3)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(2,3)

print(f"tensor_A:\n {tensor_A}, \nSize:\t {tensor_A.shape}, \nDevice:\t {tensor_A.device}\n\n")
print(f"tensor_B:\n {tensor_A}, \nSize:\t {tensor_A.shape}, \nDevice:\t {tensor_A.device}\n\n")

print("---------------------------------------------------------------------------------------------------")

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
# tensor_A_on_gpu = torch.rand((2,3), device=device)
# tensor_B_on_gpu = torch.rand((2,3), device=device)
tensor_A_on_gpu = tensor_A.to(device)
tensor_B_on_gpu = tensor_B.to(device)

print(f"tensor_A_on_gpu:\n {tensor_A_on_gpu}, \nSize:\t {tensor_A_on_gpu.shape}, \nDevice:\t {tensor_A_on_gpu.device}\n\n")
print(f"tensor_B_on_gpu:\n {tensor_B_on_gpu}, \nSize:\t {tensor_B_on_gpu.shape}, \nDevice:\t {tensor_B_on_gpu.device}\n\n")

print("---------------------------------------------------------------------------------------------------")




tensor_A:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), 
Size:	 torch.Size([2, 3]), 
Device:	 cpu


tensor_B:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), 
Size:	 torch.Size([2, 3]), 
Device:	 cpu


---------------------------------------------------------------------------------------------------
tensor_A_on_gpu:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'), 
Size:	 torch.Size([2, 3]), 
Device:	 cuda:0


tensor_B_on_gpu:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'), 
Size:	 torch.Size([2, 3]), 
Device:	 cuda:0


---------------------------------------------------------------------------------------------------



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [70]:
# Perform matmul on tensor_A and tensor_B
res_mul = tensor_A.matmul(tensor_B.T)
res_mul

tensor([[1.7622, 1.4337],
        [1.4337, 1.4338]])

### 8. Find the maximum and minimum values of the output of 7.

In [73]:
# Find max
print(f"Maximum : {res_mul.max()}")

# Find min
print(f"Minimum : {res_mul.min()}")


tensor(1.7622)
tensor(1.4337)
Maximum : 1.7622159719467163
Minimum : 1.4336886405944824


### 9. Find the maximum and minimum index values of the output of 7.

In [79]:
# Find arg max
print(f"The position of maximum {res_mul.max()} is : {res_mul.argmax()}")

# Find arg min
print(f"The position of minimum {res_mul.min()} is : {res_mul.argmin()}")


The position of maximum 1.7622159719467163 is : 0
The position of minimum 1.4336886405944824 is : 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [92]:
# Set seed
RANDOM_SEDD = 7



# Create random tensor
torch.manual_seed(RANDOM_SEED)
rand_tensor = torch.rand(1, 1, 1, 10)
print(f"rand_tensor : \n {rand_tensor}")
print(f"Size :\t {rand_tensor.shape}")
# print(f"Device :\t {rand_tensor.device}")

# torch.manual_seed(RANDOM_SEED)
print("\n---------------------------------------------------\n")

# Remove single dimensions
rand_tensor_squeezed = rand_tensor.squeeze()
print(f"rand_tensor_squeezed : \n {rand_tensor_squeezed}")
print(f"Size :\t {rand_tensor_squeezed.shape}")
# print(f"Device :\t {rand_tensor_squeezed.device}")


# Print out tensors and their shapes


rand_tensor : 
 tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
           0.6738, 0.3315]]]])
Size :	 torch.Size([1, 1, 1, 10])

---------------------------------------------------

rand_tensor_squeezed : 
 tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315])
Size :	 torch.Size([10])
